/* eslint-disable @typescript-eslint/naming-convention */
export enum ENUM_PAGINATION_ORDER_DIRECTION_TYPE {
  ASC = 'asc',
  DESC = 'desc',
}

export enum ENUM_PAGINATION_FILTER_CASE_OPTIONS {
  UPPERCASE = 'UPPERCASE',
  LOWERCASE = 'LOWERCASE',
}

export enum ENUM_PAGINATION_FILTER_DATE_TIME_OPTIONS {
  START_OF_DAY = 'START_OF_DAY',
  END_OF_DAY = 'END_OF_DAY',
}

export const PAGINATION_PER_PAGE = 20;
export const PAGINATION_MAX_PER_PAGE = 100;
export const PAGINATION_PAGE = 1;
export const PAGINATION_MAX_PAGE = 20;
export const PAGINATION_ORDER_BY = 'createdAt';
export const PAGINATION_ORDER_DIRECTION: ENUM_PAGINATION_ORDER_DIRECTION_TYPE =
  ENUM_PAGINATION_ORDER_DIRECTION_TYPE.ASC;
export const PAGINATION_AVAILABLE_ORDER_BY: string[] = ['createdAt'];
export const PAGINATION_AVAILABLE_ORDER_DIRECTION: ENUM_PAGINATION_ORDER_DIRECTION_TYPE[] = Object.values(
  ENUM_PAGINATION_ORDER_DIRECTION_TYPE,
);
